version: "3"
services:
    app:
        image: serversideup/php:8.4-fpm-nginx
        ports:
            - "80:8080" # Http
            - "443:8443" # Https
            - "5173:5173" # Vite
        environment:
            AUTORUN_ENABLED: "true"
            PHP_OPCACHE_ENABLED: "true"
        volumes:
            - ".:/var/www/html/public"

