name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  pest:
    runs-on: ubuntu-latest

    name: Pest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare application
        uses: ./.github/actions/prepare-application

      - name: Execute tests
        run: vendor/bin/pest --parallel --compact --exclude-arch

      - name: Uploade code coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-reports
          path: ./coverage

  pest-architecture:
    runs-on: ubuntu-latest

    name: Architecture Tests

    steps:
      - uses: actions/checkout@v4

      - name: Prepare application
        uses: ./.github/actions/prepare-application

      - name: Execute tests
        run: vendor/bin/pest --parallel --compact --arch --no-coverage

  vue-type-checking:
    runs-on: ubuntu-latest

    name: Vue Type-Checking

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Run vue-tsc
        run: ./node_modules/.bin/vue-tsc
