name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  pest:
    runs-on: ubuntu-latest

    name: Pest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare application
        uses: ./.github/actions/prepare-application

      - name: Execute tests
        run: vendor/bin/pest --parallel --compact --exclude-arch

  pest-architecture:
    runs-on: ubuntu-latest

    name: Architecture Tests

    steps:
      - uses: actions/checkout@v4

      - name: Prepare application
        uses: ./.github/actions/prepare-application

      - name: Execute tests
        run: vendor/bin/pest --parallel --compact --arch --no-coverage
